# Generated by Django 4.1.5 on 2023-07-24 06:43

from django.db import migrations, models
import django.db.models.deletion
import django_dag.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "职责",
            },
            bases=(models.Model, django_dag.models.NodeBase),
        ),
        migrations.CreateModel(
            name="DutyUpstreamDownstreamRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Duty_parent",
                        to="duties.duty",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Duty_child",
                        to="duties.duty",
                    ),
                ),
            ],
            options={
                "verbose_name": "职责上下游关系",
            },
        ),
        migrations.AddField(
            model_name="duty",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="duties.DutyUpstreamDownstreamRelation",
                to="duties.duty",
            ),
        ),
    ]
