# Generated by Django 4.2.4 on 2023-08-24 10:22

from django.db import migrations
import django_quanttide.models.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    django_quanttide.models.fields.IDField(
                        blank=False,
                        default=uuid.uuid4,
                        editable=False,
                        null=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_user_id",
                    django_quanttide.models.fields.IDField(
                        blank=True,
                        default=None,
                        editable=True,
                        null=True,
                        primary_key=False,
                        verbose_name="组织用户ID",
                    ),
                ),
                (
                    "created_at",
                    django_quanttide.models.fields.CreatedAtField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    django_quanttide.models.fields.UpdatedAtField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工组列表",
                "abstract": False,
            },
        ),
    ]
